pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Benose13/alx-backend-python.git',
                        credentialsId: '8a64003b-5bc1-4f5d-948f-b1afde73743d'
                    ]]
                ])
            }
        }
        
        stage('Set up Python environment') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }
        
        stage('Run Tests with pytest') {
            steps {
                sh '. venv/bin/activate && pytest --junitxml=test-results.xml --cov=./ --cov-report=xml'
            }
            post {
                always {
                    junit 'test-results.xml'
                    publishHTML([
                        target: [
                            allowMissing: false,
                            alwaysLinkToLastBuild: false,
                            keepAll: true,
                            reportDir: 'htmlcov',
                            reportFiles: 'index.html',
                            reportName: 'Coverage Report'
                        ]
                    ])
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed - check test results and coverage report'
        }
        failure {
            echo '❌ Pipeline failed — check logs and test report.'
        }
    }
}